# Generated by Django 4.0.2 on 2022-02-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='last_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
