# Generated by Django 4.0.2 on 2022-02-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employees_egn_employees_job_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employees',
            name='egn',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='EGN'),
        ),
    ]
