# Generated by Django 4.0.2 on 2022-02-26 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employees_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('dead_line', models.DateField(blank=True, null=True)),
                ('employees', models.ManyToManyField(null=True, to='employees.Employees')),
            ],
        ),
    ]
