# Generated by Django 4.0.2 on 2022-02-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_alter_department_created_on_alter_employees_egn'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
