# Generated by Django 4.0.3 on 2022-04-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('employees', models.ManyToManyField(to='employees.employee')),
            ],
        ),
    ]
