# Generated by Django 4.0.4 on 2022-04-13 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='user_profile',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='musicapp.profile'),
            preserve_default=False,
        ),
    ]
