# Generated by Django 4.0.4 on 2022-04-15 15:22

import django.core.validators
from django.db import migrations, models
import my_music_app.musicapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_album_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='user_profile',
        ),
        migrations.AlterField(
            model_name='album',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), my_music_app.musicapp.models.validate_only_letters_and_underscores]),
        ),
    ]
