# from project.controller import Controller
#
# controller = Controller()
# print(controller.add_aquarium('FreshwaterAquarium','Aquarium 1'))
# print(controller.add_aquarium('SaltwaterAquarium','Aquarium 2'))
# print(controller.add_decoration('Plant'))
# print(controller.add_decoration('Plant'))
# print(controller.add_decoration('Ornament'))
# print(controller.add_decoration('Ornament'))
# print(controller.insert_decoration('Aquarium 1', 'Plant'))
# print(controller.insert_decoration('Aquarium 1', 'Ornament'))
# print(controller.insert_decoration('Aquarium 2', 'Plant'))
# print(controller.insert_decoration('Aquarium 2', 'Ornament'))
# print(controller.add_fish('Aquarium 1', 'FreshwaterFish', 'Nemo', 'species', 2.8))
# print(controller.add_fish('Aquarium 1', 'FreshwaterFish', 'Nemo 2', 'species', 2.8))
# print(controller.add_fish('Aquarium 1', 'FreshwaterFish', 'Nemo 3', 'species', 2.8))
# print(controller.add_fish('Aquarium 1', 'FreshwaterFish', 'Nemo 4', 'species', 2.8))
# print(controller.calculate_value('Aquarium 1'))
# print(controller.calculate_value('Aquarium 2'))
# print(controller.feed_fish('Aquarium 1'))
# print(controller.feed_fish('Aquarium 2'))
# print(controller.report())